version: '2'
services:
    springbootreactjssample2-app:
        image: springbootreactjssample2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springbootreactjssample2-mysql:3306/springbootreactjssample2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springbootreactjssample2-mysql:
        extends:
            file: mysql.yml
            service: springbootreactjssample2-mysql
